// vocab.js — Bộ từ vựng theo chủ đề cho app
// Batch 1: 150 từ / 10 chủ đề (mục tiêu: 1000)
// Mỗi mục: { c: chủ đề, v: từ, m: "(loại từ) nghĩa", e: ví dụ tiếng Anh, d: dịch tiếng Việt, col: các cụm hay đi với từ }
// id được suy ra tự động = c + "::" + v

const raw = [
  // ===== Con người & Tính cách =====
  { c: "Con người & Tính cách", v: "reliable", m: "(adj) đáng tin cậy", e: "She's the most reliable person on the team — she never misses a deadline.", d: "Cô ấy là người đáng tin cậy nhất nhóm — chưa bao giờ trễ hạn.", col: "a reliable source · reliable information · a reliable friend" },
  { c: "Con người & Tính cách", v: "stubborn", m: "(adj) bướng bỉnh, cứng đầu", e: "He's too stubborn to admit he was wrong.", d: "Anh ấy quá cứng đầu để thừa nhận mình sai.", col: "stubborn as a mule · a stubborn child · stubbornly refuse" },
  { c: "Con người & Tính cách", v: "genuine", m: "(adj) chân thật, thật lòng", e: "Her smile felt genuine, not forced.", d: "Nụ cười của cô ấy rất chân thật, không gượng gạo.", col: "a genuine smile · genuine concern · genuine interest" },
  { c: "Con người & Tính cách", v: "outgoing", m: "(adj) hướng ngoại, dễ gần", e: "Being outgoing helps a lot when you move to a new city.", d: "Tính hướng ngoại giúp ích nhiều khi bạn chuyển đến thành phố mới.", col: "an outgoing personality · friendly and outgoing" },
  { c: "Con người & Tính cách", v: "blunt", m: "(adj) thẳng thừng (nói thật, dễ mất lòng)", e: "I'll be blunt: the plan won't work.", d: "Tôi nói thẳng nhé: kế hoạch này sẽ không ổn.", col: "to be blunt · blunt honesty · a blunt remark" },
  { c: "Con người & Tính cách", v: "humble", m: "(adj) khiêm tốn", e: "Despite his success, he stayed humble.", d: "Dù thành công, anh ấy vẫn khiêm tốn.", col: "humble beginnings · stay humble · a humble person" },
  { c: "Con người & Tính cách", v: "ambitious", m: "(adj) tham vọng, nhiều hoài bão", e: "She's ambitious and wants to run her own company someday.", d: "Cô ấy nhiều hoài bão và muốn có công ty riêng một ngày nào đó.", col: "an ambitious goal · highly ambitious · an ambitious plan" },
  { c: "Con người & Tính cách", v: "easygoing", m: "(adj) dễ tính, thoải mái", e: "My roommate is easygoing, so we never argue.", d: "Bạn cùng phòng của tôi rất dễ tính nên chúng tôi không bao giờ cãi nhau.", col: "an easygoing nature · easygoing and relaxed" },
  { c: "Con người & Tính cách", v: "self-conscious", m: "(adj) ngại ngùng, hay để ý người khác nghĩ gì", e: "I feel self-conscious speaking English in front of crowds.", d: "Tôi thấy ngại khi nói tiếng Anh trước đám đông.", col: "feel self-conscious about · self-conscious about my looks" },
  { c: "Con người & Tính cách", v: "witty", m: "(adj) hóm hỉnh, dí dỏm", e: "His witty comments always make the meeting fun.", d: "Những câu hóm hỉnh của anh ấy luôn làm buổi họp vui hơn.", col: "a witty remark · quick-witted · witty banter" },
  { c: "Con người & Tính cách", v: "down-to-earth", m: "(adj) giản dị, thực tế", e: "She's a famous actress but very down-to-earth.", d: "Cô ấy là diễn viên nổi tiếng nhưng rất giản dị.", col: "a down-to-earth person · refreshingly down-to-earth" },
  { c: "Con người & Tính cách", v: "introverted", m: "(adj) hướng nội", e: "Introverted people often recharge by spending time alone.", d: "Người hướng nội thường nạp lại năng lượng bằng cách ở một mình.", col: "shy and introverted · an introverted person" },
  { c: "Con người & Tính cách", v: "considerate", m: "(adj) chu đáo, biết nghĩ cho người khác", e: "It was considerate of you to call and check on me.", d: "Bạn thật chu đáo khi gọi hỏi thăm tôi.", col: "considerate of others · kind and considerate" },
  { c: "Con người & Tính cách", v: "moody", m: "(adj) thất thường, hay đổi tâm trạng", e: "He's been really moody since he lost his job.", d: "Anh ấy khá thất thường từ khi mất việc.", col: "a moody teenager · moody and unpredictable" },
  { c: "Con người & Tính cách", v: "laid-back", m: "(adj) thư thái, không căng thẳng", e: "The boss has a laid-back style; he trusts us to manage our time.", d: "Sếp có phong cách thoải mái; ông tin chúng tôi tự quản lý thời gian.", col: "a laid-back attitude · laid-back and relaxed" },

  // ===== Công việc & Sự nghiệp =====
  { c: "Công việc & Sự nghiệp", v: "deadline", m: "(n) hạn chót", e: "We're racing to meet the deadline.", d: "Chúng tôi đang chạy nước rút cho kịp hạn chót.", col: "meet a deadline · miss the deadline · a tight deadline" },
  { c: "Công việc & Sự nghiệp", v: "multitask", m: "(v) làm nhiều việc cùng lúc", e: "I can't multitask well; I focus better on one thing.", d: "Tôi làm nhiều việc cùng lúc không tốt; tập trung từng việc thì hơn.", col: "the ability to multitask · multitask under pressure" },
  { c: "Công việc & Sự nghiệp", v: "overworked", m: "(adj) làm việc quá sức", e: "Half the staff feel overworked and underpaid.", d: "Nửa số nhân viên thấy bị vắt sức mà lương thấp.", col: "overworked and underpaid · feel overworked" },
  { c: "Công việc & Sự nghiệp", v: "promotion", m: "(n) sự thăng chức", e: "She got a promotion after two years.", d: "Cô ấy được thăng chức sau hai năm.", col: "get a promotion · earn a promotion · a well-deserved promotion" },
  { c: "Công việc & Sự nghiệp", v: "burnout", m: "(n) sự kiệt sức (vì làm việc)", e: "Take regular breaks to avoid burnout.", d: "Hãy nghỉ ngơi đều đặn để tránh kiệt sức.", col: "avoid burnout · suffer burnout · job burnout" },
  { c: "Công việc & Sự nghiệp", v: "networking", m: "(n) việc xây dựng quan hệ", e: "Networking helped me find this job.", d: "Việc xây dựng quan hệ giúp tôi tìm được công việc này.", col: "a networking event · professional networking · networking skills" },
  { c: "Công việc & Sự nghiệp", v: "workload", m: "(n) khối lượng công việc", e: "My workload doubled this month.", d: "Khối lượng công việc của tôi tăng gấp đôi tháng này.", col: "a heavy workload · manage your workload · reduce the workload" },
  { c: "Công việc & Sự nghiệp", v: "freelance", m: "(adj/v) làm tự do", e: "He quit to work freelance from home.", d: "Anh ấy nghỉ việc để làm tự do tại nhà.", col: "work freelance · a freelance writer · go freelance" },
  { c: "Công việc & Sự nghiệp", v: "resign", m: "(v) từ chức, xin nghỉ việc", e: "She decided to resign and start her own business.", d: "Cô ấy quyết định nghỉ việc để khởi nghiệp.", col: "resign from a job · decide to resign · hand in your resignation" },
  { c: "Công việc & Sự nghiệp", v: "demanding", m: "(adj) đòi hỏi cao, vất vả", e: "It's a demanding job but very rewarding.", d: "Đó là công việc vất vả nhưng rất xứng đáng.", col: "a demanding job · a demanding boss · physically demanding" },
  { c: "Công việc & Sự nghiệp", v: "colleague", m: "(n) đồng nghiệp", e: "My colleagues are friendly and supportive.", d: "Đồng nghiệp của tôi thân thiện và hỗ trợ.", col: "a close colleague · a former colleague · work colleagues" },
  { c: "Công việc & Sự nghiệp", v: "overtime", m: "(n) giờ làm thêm", e: "I worked overtime three nights this week.", d: "Tôi làm thêm giờ ba tối tuần này.", col: "work overtime · paid overtime · do overtime" },
  { c: "Công việc & Sự nghiệp", v: "expertise", m: "(n) chuyên môn", e: "We need someone with marketing expertise.", d: "Chúng tôi cần người có chuyên môn marketing.", col: "technical expertise · areas of expertise · share your expertise" },
  { c: "Công việc & Sự nghiệp", v: "proactive", m: "(adj) chủ động", e: "Be proactive — don't wait to be told.", d: "Hãy chủ động — đừng chờ người ta bảo.", col: "a proactive approach · be proactive · proactive measures" },
  { c: "Công việc & Sự nghiệp", v: "micromanage", m: "(v) quản lý kiểu xét nét từng li", e: "Nobody likes a boss who micromanages.", d: "Không ai thích sếp soi từng chút một.", col: "micromanage every detail · tend to micromanage" },

  // ===== Cảm xúc & Tâm trạng =====
  { c: "Cảm xúc & Tâm trạng", v: "overwhelmed", m: "(adj) choáng ngợp, quá tải", e: "I feel overwhelmed by all these tasks.", d: "Tôi thấy quá tải với đống việc này.", col: "feel overwhelmed · completely overwhelmed · overwhelmed with work" },
  { c: "Cảm xúc & Tâm trạng", v: "anxious", m: "(adj) lo lắng, bồn chồn", e: "She's anxious about the interview tomorrow.", d: "Cô ấy lo lắng về buổi phỏng vấn ngày mai.", col: "anxious about · feel anxious · an anxious feeling" },
  { c: "Cảm xúc & Tâm trạng", v: "content", m: "(adj, đọc /kənˈtent/) hài lòng, mãn nguyện", e: "He's content with a simple, quiet life.", d: "Anh ấy mãn nguyện với cuộc sống giản dị, yên bình.", col: "content with life · perfectly content · feel content" },
  { c: "Cảm xúc & Tâm trạng", v: "frustrated", m: "(adj) bực bội, nản lòng", e: "I'm frustrated that the app keeps crashing.", d: "Tôi bực vì cái app cứ bị treo.", col: "get frustrated · frustrated with · increasingly frustrated" },
  { c: "Cảm xúc & Tâm trạng", v: "relieved", m: "(adj) nhẹ nhõm", e: "I was relieved when the test was over.", d: "Tôi thấy nhẹ nhõm khi thi xong.", col: "relieved to hear · feel relieved · a relieved sigh" },
  { c: "Cảm xúc & Tâm trạng", v: "nostalgic", m: "(adj) hoài niệm", e: "This song makes me nostalgic for high school.", d: "Bài hát này khiến tôi hoài niệm thời cấp ba.", col: "feel nostalgic · nostalgic about the past · a nostalgic mood" },
  { c: "Cảm xúc & Tâm trạng", v: "grumpy", m: "(adj) cáu kỉnh (nhất là khi mệt)", e: "I'm grumpy before my morning coffee.", d: "Tôi cáu kỉnh khi chưa uống cà phê sáng.", col: "a grumpy mood · grumpy in the morning · a grumpy old man" },
  { c: "Cảm xúc & Tâm trạng", v: "thrilled", m: "(adj) cực kỳ vui mừng", e: "She was thrilled to get the scholarship.", d: "Cô ấy mừng rơn khi nhận được học bổng.", col: "thrilled to bits · absolutely thrilled · thrilled about the news" },
  { c: "Cảm xúc & Tâm trạng", v: "insecure", m: "(adj) thiếu tự tin, bất an", e: "He feels insecure about his accent.", d: "Anh ấy thấy thiếu tự tin về giọng của mình.", col: "feel insecure · insecure about · deeply insecure" },
  { c: "Cảm xúc & Tâm trạng", v: "envious", m: "(adj) ghen tị", e: "I'm a little envious of their trip to Japan.", d: "Tôi hơi ghen tị với chuyến đi Nhật của họ.", col: "envious of · green with envy · slightly envious" },
  { c: "Cảm xúc & Tâm trạng", v: "exhausted", m: "(adj) kiệt sức", e: "After the hike, we were completely exhausted.", d: "Sau chuyến leo núi, chúng tôi kiệt sức hoàn toàn.", col: "completely exhausted · physically exhausted · feel exhausted" },
  { c: "Cảm xúc & Tâm trạng", v: "proud", m: "(adj) tự hào", e: "I'm proud of how far you've come.", d: "Tôi tự hào về chặng đường bạn đã đi.", col: "proud of · immensely proud · a proud moment" },
  { c: "Cảm xúc & Tâm trạng", v: "uneasy", m: "(adj) bất an, không yên lòng", e: "Something about the deal made me uneasy.", d: "Có gì đó về thương vụ khiến tôi thấy bất an.", col: "feel uneasy · an uneasy feeling · uneasy about" },
  { c: "Cảm xúc & Tâm trạng", v: "cheerful", m: "(adj) vui vẻ, tươi tắn", e: "She greeted everyone with a cheerful smile.", d: "Cô ấy chào mọi người bằng nụ cười tươi tắn.", col: "a cheerful smile · bright and cheerful · in a cheerful mood" },
  { c: "Cảm xúc & Tâm trạng", v: "heartbroken", m: "(adj) đau lòng, tan vỡ", e: "He was heartbroken after the breakup.", d: "Anh ấy đau lòng sau khi chia tay.", col: "absolutely heartbroken · leave someone heartbroken" },

  // ===== Giao tiếp & Quan hệ =====
  { c: "Giao tiếp & Quan hệ", v: "awkward", m: "(adj) ngượng ngùng, khó xử", e: "There was an awkward silence after his joke.", d: "Có một khoảng im lặng khó xử sau câu đùa của anh ấy.", col: "an awkward silence · feel awkward · an awkward situation" },
  { c: "Giao tiếp & Quan hệ", v: "apologize", m: "(v) xin lỗi", e: "He apologized for being late.", d: "Anh ấy xin lỗi vì đến muộn.", col: "apologize for · apologize to someone · sincerely apologize" },
  { c: "Giao tiếp & Quan hệ", v: "gossip", m: "(n/v) buôn chuyện, tin đồn", e: "I try not to gossip about coworkers.", d: "Tôi cố không buôn chuyện về đồng nghiệp.", col: "spread gossip · office gossip · gossip about" },
  { c: "Giao tiếp & Quan hệ", v: "argue", m: "(v) tranh cãi", e: "They argue a lot but still love each other.", d: "Họ hay cãi nhau nhưng vẫn yêu nhau.", col: "argue with · argue about · argue over money" },
  { c: "Giao tiếp & Quan hệ", v: "compliment", m: "(n/v) lời khen / khen", e: "She gave me a nice compliment on my work.", d: "Cô ấy khen công việc của tôi rất hay.", col: "pay someone a compliment · take it as a compliment · a genuine compliment" },
  { c: "Giao tiếp & Quan hệ", v: "misunderstand", m: "(v) hiểu lầm", e: "I think you misunderstood what I meant.", d: "Tôi nghĩ bạn đã hiểu lầm ý tôi.", col: "misunderstand each other · easily misunderstood · don't misunderstand me" },
  { c: "Giao tiếp & Quan hệ", v: "small talk", m: "(n) chuyện phiếm, nói chuyện xã giao", e: "I'm bad at small talk with strangers.", d: "Tôi dở khoản nói chuyện phiếm với người lạ.", col: "make small talk · good at small talk · awkward small talk" },
  { c: "Giao tiếp & Quan hệ", v: "sincere", m: "(adj) chân thành", e: "Please accept my sincere apology.", d: "Mong bạn nhận lời xin lỗi chân thành của tôi.", col: "a sincere apology · my sincere thanks · sincere and honest" },
  { c: "Giao tiếp & Quan hệ", v: "tactful", m: "(adj) khéo léo, tế nhị", e: "She's tactful when giving feedback.", d: "Cô ấy rất tế nhị khi góp ý.", col: "a tactful way · tactful about · diplomatic and tactful" },
  { c: "Giao tiếp & Quan hệ", v: "confront", m: "(v) đối chất, đối mặt", e: "I had to confront him about the missing money.", d: "Tôi phải đối chất với anh ta về số tiền thất lạc.", col: "confront someone about · confront a problem · confront your fears" },
  { c: "Giao tiếp & Quan hệ", v: "acquaintance", m: "(n) người quen (không thân)", e: "He's just an acquaintance, not a close friend.", d: "Anh ấy chỉ là người quen, không phải bạn thân.", col: "a mutual acquaintance · a casual acquaintance · an old acquaintance" },
  { c: "Giao tiếp & Quan hệ", v: "reconcile", m: "(v) làm hòa, hòa giải", e: "The two friends finally reconciled.", d: "Hai người bạn cuối cùng cũng làm hòa.", col: "reconcile with · reconcile their differences · finally reconcile" },
  { c: "Giao tiếp & Quan hệ", v: "bond", m: "(n/v) sự gắn kết / gắn bó", e: "The trip helped the team bond.", d: "Chuyến đi giúp cả nhóm gắn kết hơn.", col: "form a bond · a strong bond · bond over" },
  { c: "Giao tiếp & Quan hệ", v: "vague", m: "(adj) mơ hồ, không rõ ràng", e: "His answer was vague, so I asked again.", d: "Câu trả lời của anh ấy mơ hồ nên tôi hỏi lại.", col: "a vague idea · vague about · remain vague" },
  { c: "Giao tiếp & Quan hệ", v: "rapport", m: "(n) sự gần gũi, hợp ý", e: "A good teacher builds rapport with students.", d: "Giáo viên giỏi tạo được sự gần gũi với học trò.", col: "build rapport · a good rapport · establish rapport" },

  // ===== Học tập & Tư duy =====
  { c: "Học tập & Tư duy", v: "procrastinate", m: "(v) trì hoãn, chần chừ", e: "I always procrastinate before big exams.", d: "Tôi luôn chần chừ trước các kỳ thi lớn.", col: "tend to procrastinate · procrastinate on · stop procrastinating" },
  { c: "Học tập & Tư duy", v: "memorize", m: "(v) học thuộc", e: "Don't just memorize — try to understand.", d: "Đừng chỉ học thuộc — hãy cố hiểu.", col: "memorize by heart · memorize a list · hard to memorize" },
  { c: "Học tập & Tư duy", v: "curious", m: "(adj) tò mò, ham hiểu biết", e: "Stay curious and keep asking questions.", d: "Hãy giữ sự tò mò và tiếp tục đặt câu hỏi.", col: "curious about · naturally curious · a curious mind" },
  { c: "Học tập & Tư duy", v: "distracted", m: "(adj) bị phân tâm", e: "I get distracted by my phone while studying.", d: "Tôi bị điện thoại làm phân tâm khi học.", col: "easily distracted · get distracted · distracted by" },
  { c: "Học tập & Tư duy", v: "grasp", m: "(v) nắm bắt, hiểu được", e: "It took me a while to grasp the concept.", d: "Tôi mất một lúc mới nắm được khái niệm này.", col: "grasp the concept · grasp the basics · hard to grasp" },
  { c: "Học tập & Tư duy", v: "insight", m: "(n) sự thấu hiểu, góc nhìn sâu", e: "The book gave me real insight into how habits form.", d: "Cuốn sách cho tôi cái nhìn sâu về cách thói quen hình thành.", col: "gain insight into · a valuable insight · deep insight" },
  { c: "Học tập & Tư duy", v: "brainstorm", m: "(v) động não, nghĩ ý tưởng", e: "Let's brainstorm a few ideas first.", d: "Hãy động não nghĩ vài ý trước đã.", col: "brainstorm ideas · a brainstorming session · brainstorm together" },
  { c: "Học tập & Tư duy", v: "overthink", m: "(v) suy nghĩ quá nhiều", e: "Stop overthinking it and just start.", d: "Đừng nghĩ quá nhiều, cứ bắt đầu thôi.", col: "overthink everything · stop overthinking · tend to overthink" },
  { c: "Học tập & Tư duy", v: "mindset", m: "(n) tư duy, lối nghĩ", e: "A growth mindset means you believe you can improve.", d: "Tư duy cầu tiến nghĩa là tin mình có thể tiến bộ.", col: "a growth mindset · a positive mindset · the right mindset" },
  { c: "Học tập & Tư duy", v: "recall", m: "(v) nhớ lại", e: "I can't recall her name right now.", d: "Tôi không nhớ ra tên cô ấy lúc này.", col: "recall the details · vaguely recall · if I recall correctly" },
  { c: "Học tập & Tư duy", v: "tedious", m: "(adj) tẻ nhạt, nhàm chán (lặp đi lặp lại)", e: "Filling out forms is tedious but necessary.", d: "Điền biểu mẫu thì tẻ nhạt nhưng cần thiết.", col: "a tedious task · long and tedious · tedious work" },
  { c: "Học tập & Tư duy", v: "fluent", m: "(adj) trôi chảy, lưu loát", e: "She's fluent in three languages.", d: "Cô ấy nói lưu loát ba thứ tiếng.", col: "fluent in English · become fluent · a fluent speaker" },
  { c: "Học tập & Tư duy", v: "comprehend", m: "(v) hiểu thấu (trang trọng hơn 'understand')", e: "The text was too complex for me to comprehend.", d: "Đoạn văn quá phức tạp để tôi hiểu thấu.", col: "hard to comprehend · fully comprehend · comprehend the meaning" },
  { c: "Học tập & Tư duy", v: "self-taught", m: "(adj) tự học", e: "He's a self-taught programmer.", d: "Anh ấy là lập trình viên tự học.", col: "a self-taught artist · entirely self-taught" },
  { c: "Học tập & Tư duy", v: "challenging", m: "(adj) đầy thử thách", e: "Learning a new alphabet is challenging but fun.", d: "Học một bảng chữ cái mới đầy thử thách nhưng vui.", col: "a challenging task · intellectually challenging · challenging but rewarding" },

  // ===== Sức khỏe & Cơ thể =====
  { c: "Sức khỏe & Cơ thể", v: "exhausting", m: "(adj) làm mệt lử", e: "The night shift is exhausting.", d: "Ca đêm làm người ta mệt lử.", col: "physically exhausting · an exhausting day · mentally exhausting" },
  { c: "Sức khỏe & Cơ thể", v: "recover", m: "(v) hồi phục", e: "It took a week to recover from the flu.", d: "Tôi mất một tuần để hồi phục sau cơn cúm.", col: "recover from illness · fully recover · recover quickly" },
  { c: "Sức khỏe & Cơ thể", v: "sore", m: "(adj) đau nhức (cơ bắp)", e: "My legs are sore after the gym.", d: "Chân tôi đau nhức sau khi tập gym.", col: "sore muscles · a sore throat · sore after exercise" },
  { c: "Sức khỏe & Cơ thể", v: "nutritious", m: "(adj) bổ dưỡng", e: "She cooks simple but nutritious meals.", d: "Cô ấy nấu các bữa đơn giản nhưng bổ dưỡng.", col: "a nutritious meal · healthy and nutritious · nutritious food" },
  { c: "Sức khỏe & Cơ thể", v: "immune", m: "(adj) miễn dịch", e: "Exercise can strengthen your immune system.", d: "Vận động có thể tăng cường hệ miễn dịch.", col: "the immune system · boost your immune system · a weak immune system" },
  { c: "Sức khỏe & Cơ thể", v: "dizzy", m: "(adj) chóng mặt", e: "I felt dizzy after standing up too fast.", d: "Tôi thấy chóng mặt sau khi đứng dậy quá nhanh.", col: "feel dizzy · a dizzy spell · dizzy and lightheaded" },
  { c: "Sức khỏe & Cơ thể", v: "workout", m: "(n) buổi tập luyện", e: "A short workout in the morning wakes me up.", d: "Một buổi tập ngắn buổi sáng giúp tôi tỉnh táo.", col: "a tough workout · do a workout · a morning workout" },
  { c: "Sức khỏe & Cơ thể", v: "posture", m: "(n) tư thế (ngồi/đứng)", e: "Sitting all day ruins your posture.", d: "Ngồi cả ngày làm hỏng tư thế của bạn.", col: "good posture · poor posture · improve your posture" },
  { c: "Sức khỏe & Cơ thể", v: "insomnia", m: "(n) chứng mất ngủ", e: "Stress often causes insomnia.", d: "Căng thẳng thường gây mất ngủ.", col: "suffer from insomnia · chronic insomnia · cure insomnia" },
  { c: "Sức khỏe & Cơ thể", v: "heal", m: "(v) lành lại, chữa lành", e: "The wound will heal in a few days.", d: "Vết thương sẽ lành trong vài ngày.", col: "heal quickly · time heals · heal a wound" },
  { c: "Sức khỏe & Cơ thể", v: "fatigue", m: "(n) sự mệt mỏi (kéo dài)", e: "Constant fatigue can be a warning sign.", d: "Mệt mỏi triền miên có thể là dấu hiệu cảnh báo.", col: "chronic fatigue · mental fatigue · suffer from fatigue" },
  { c: "Sức khỏe & Cơ thể", v: "fit", m: "(adj) khỏe khoắn, cân đối", e: "He stays fit by cycling to work.", d: "Anh ấy giữ dáng bằng cách đạp xe đi làm.", col: "keep fit · stay fit · physically fit" },
  { c: "Sức khỏe & Cơ thể", v: "allergic", m: "(adj) dị ứng", e: "I'm allergic to peanuts.", d: "Tôi bị dị ứng đậu phộng.", col: "allergic to · an allergic reaction · severely allergic" },
  { c: "Sức khỏe & Cơ thể", v: "hydrate", m: "(v) bổ sung nước cho cơ thể", e: "Remember to hydrate during exercise.", d: "Nhớ uống đủ nước khi tập luyện.", col: "stay hydrated · hydrate properly · drink to hydrate" },
  { c: "Sức khỏe & Cơ thể", v: "drained", m: "(adj) cạn kiệt năng lượng", e: "I feel drained after a long meeting.", d: "Tôi thấy cạn kiệt năng lượng sau buổi họp dài.", col: "feel drained · emotionally drained · completely drained" },

  // ===== Tiền bạc & Mua sắm =====
  { c: "Tiền bạc & Mua sắm", v: "afford", m: "(v) đủ tiền mua", e: "I can't afford a new laptop right now.", d: "Tôi chưa đủ tiền mua laptop mới lúc này.", col: "can't afford · afford to buy · barely afford" },
  { c: "Tiền bạc & Mua sắm", v: "budget", m: "(n/v) ngân sách / lập ngân sách", e: "I budget carefully each month.", d: "Tôi lập ngân sách kỹ mỗi tháng.", col: "stick to a budget · a tight budget · on a budget" },
  { c: "Tiền bạc & Mua sắm", v: "splurge", m: "(v) vung tiền, chi mạnh tay", e: "I splurged on a nice dinner to celebrate.", d: "Tôi chi mạnh tay cho bữa tối ngon để ăn mừng.", col: "splurge on · a little splurge · splurge occasionally" },
  { c: "Tiền bạc & Mua sắm", v: "bargain", m: "(n) món hời", e: "This jacket was a real bargain.", d: "Cái áo khoác này đúng là món hời.", col: "a real bargain · bargain hunting · a bargain price" },
  { c: "Tiền bạc & Mua sắm", v: "refund", m: "(n/v) sự hoàn tiền / hoàn tiền", e: "I asked for a refund on the broken item.", d: "Tôi yêu cầu hoàn tiền cho món hàng hỏng.", col: "ask for a refund · a full refund · get a refund" },
  { c: "Tiền bạc & Mua sắm", v: "pricey", m: "(adj, khẩu ngữ) hơi đắt", e: "That café is nice but a bit pricey.", d: "Quán cà phê đó đẹp nhưng hơi đắt.", col: "a bit pricey · rather pricey · pricey but worth it" },
  { c: "Tiền bạc & Mua sắm", v: "discount", m: "(n) sự giảm giá", e: "They offer a student discount.", d: "Họ có giảm giá cho sinh viên.", col: "a big discount · get a discount · a student discount" },
  { c: "Tiền bạc & Mua sắm", v: "broke", m: "(adj, khẩu ngữ) cháy túi, hết tiền", e: "I'm broke until payday.", d: "Tôi cháy túi cho đến ngày lương.", col: "flat broke · go broke · broke until payday" },
  { c: "Tiền bạc & Mua sắm", v: "invest", m: "(v) đầu tư", e: "She invests a little money every month.", d: "Cô ấy đầu tư một ít tiền mỗi tháng.", col: "invest in · invest money · a smart investment" },
  { c: "Tiền bạc & Mua sắm", v: "owe", m: "(v) nợ, mắc nợ", e: "I still owe my friend twenty dollars.", d: "Tôi vẫn nợ bạn tôi hai mươi đô.", col: "owe money · owe someone · owe a favor" },
  { c: "Tiền bạc & Mua sắm", v: "affordable", m: "(adj) phải chăng, hợp túi tiền", e: "We need an affordable place to live.", d: "Chúng tôi cần một chỗ ở hợp túi tiền.", col: "an affordable price · affordable housing · cheap and affordable" },
  { c: "Tiền bạc & Mua sắm", v: "save up", m: "(phr.v) để dành, tích góp", e: "I'm saving up for a trip to Korea.", d: "Tôi đang để dành cho chuyến đi Hàn Quốc.", col: "save up for · save up money · save up enough" },
  { c: "Tiền bạc & Mua sắm", v: "overspend", m: "(v) chi tiêu quá tay", e: "It's easy to overspend during sales.", d: "Rất dễ chi tiêu quá tay vào mùa giảm giá.", col: "overspend on · tend to overspend · overspend your budget" },
  { c: "Tiền bạc & Mua sắm", v: "worth", m: "(adj/n) đáng giá", e: "The course was worth every penny.", d: "Khóa học đáng từng đồng.", col: "worth it · worth the money · well worth" },
  { c: "Tiền bạc & Mua sắm", v: "tip", m: "(n) tiền boa", e: "In the US, it's normal to leave a tip.", d: "Ở Mỹ, để lại tiền boa là chuyện bình thường.", col: "leave a tip · a generous tip · a 10% tip" },

  // ===== Công nghệ & Đời sống số =====
  { c: "Công nghệ & Đời sống số", v: "scroll", m: "(v) lướt (màn hình)", e: "I scroll through my phone too much before bed.", d: "Tôi lướt điện thoại quá nhiều trước khi ngủ.", col: "scroll through · endless scrolling · scroll down" },
  { c: "Công nghệ & Đời sống số", v: "update", m: "(n/v) bản cập nhật / cập nhật", e: "The app needs an update.", d: "Ứng dụng cần được cập nhật.", col: "a software update · install an update · update the app" },
  { c: "Công nghệ & Đời sống số", v: "glitch", m: "(n) trục trặc nhỏ (kỹ thuật)", e: "The video had a small glitch.", d: "Video bị một trục trặc nhỏ.", col: "a technical glitch · a minor glitch · fix a glitch" },
  { c: "Công nghệ & Đời sống số", v: "notification", m: "(n) thông báo", e: "I turned off notifications to focus.", d: "Tôi tắt thông báo để tập trung.", col: "a push notification · turn off notifications · get a notification" },
  { c: "Công nghệ & Đời sống số", v: "log in", m: "(phr.v) đăng nhập", e: "I can't log in to my account.", d: "Tôi không đăng nhập được vào tài khoản.", col: "log in to · log in with · fail to log in" },
  { c: "Công nghệ & Đời sống số", v: "browse", m: "(v) duyệt, xem lướt", e: "I like to browse online before buying.", d: "Tôi thích xem lướt trên mạng trước khi mua.", col: "browse the web · browse through · browse online" },
  { c: "Công nghệ & Đời sống số", v: "upload", m: "(v) tải lên", e: "She uploaded the photos to the cloud.", d: "Cô ấy tải ảnh lên đám mây.", col: "upload a file · upload to the cloud · upload speed" },
  { c: "Công nghệ & Đời sống số", v: "crash", m: "(v) (máy/app) sập, treo", e: "My laptop crashed and I lost the file.", d: "Laptop của tôi bị treo và tôi mất file.", col: "the system crashed · a sudden crash · crash repeatedly" },
  { c: "Công nghệ & Đời sống số", v: "user-friendly", m: "(adj) dễ sử dụng", e: "The new design is more user-friendly.", d: "Thiết kế mới dễ dùng hơn.", col: "a user-friendly interface · simple and user-friendly" },
  { c: "Công nghệ & Đời sống số", v: "addictive", m: "(adj) gây nghiện", e: "Short videos are dangerously addictive.", d: "Video ngắn gây nghiện một cách nguy hiểm.", col: "highly addictive · dangerously addictive · an addictive game" },
  { c: "Công nghệ & Đời sống số", v: "backup", m: "(n) bản sao lưu", e: "Always keep a backup of your work.", d: "Luôn giữ một bản sao lưu công việc của bạn.", col: "a backup copy · make a backup · backup your data" },
  { c: "Công nghệ & Đời sống số", v: "outdated", m: "(adj) lỗi thời", e: "My phone is outdated and very slow.", d: "Điện thoại của tôi lỗi thời và rất chậm.", col: "outdated software · hopelessly outdated · an outdated phone" },
  { c: "Công nghệ & Đời sống số", v: "streaming", m: "(n/adj) phát trực tuyến", e: "We spent the night streaming a new series.", d: "Chúng tôi xem trực tuyến một bộ phim mới cả đêm.", col: "a streaming service · streaming online · live streaming" },
  { c: "Công nghệ & Đời sống số", v: "wireless", m: "(adj) không dây", e: "These wireless earbuds are great.", d: "Tai nghe không dây này rất tốt.", col: "a wireless connection · wireless headphones · go wireless" },
  { c: "Công nghệ & Đời sống số", v: "overload", m: "(n/v) sự quá tải / làm quá tải", e: "Too many tabs cause information overload.", d: "Quá nhiều tab gây quá tải thông tin.", col: "information overload · sensory overload · overload the system" },

  // ===== Du lịch & Địa điểm =====
  { c: "Du lịch & Địa điểm", v: "commute", m: "(n/v) việc đi lại (đi làm)", e: "My commute takes an hour each way.", d: "Quãng đường đi làm của tôi mất một tiếng mỗi chiều.", col: "a daily commute · a long commute · commute to work" },
  { c: "Du lịch & Địa điểm", v: "crowded", m: "(adj) đông đúc", e: "The market was crowded on the weekend.", d: "Khu chợ đông đúc vào cuối tuần.", col: "a crowded street · packed and crowded · crowded with tourists" },
  { c: "Du lịch & Địa điểm", v: "scenic", m: "(adj) có phong cảnh đẹp", e: "We took the scenic route along the coast.", d: "Chúng tôi đi đường ven biển có phong cảnh đẹp.", col: "a scenic route · a scenic view · scenic spots" },
  { c: "Du lịch & Địa điểm", v: "depart", m: "(v) khởi hành", e: "The train departs at 9 sharp.", d: "Tàu khởi hành đúng 9 giờ.", col: "depart on time · depart from · the departing flight" },
  { c: "Du lịch & Địa điểm", v: "luggage", m: "(n) hành lý", e: "I packed my luggage the night before.", d: "Tôi xếp hành lý từ tối hôm trước.", col: "carry-on luggage · pack your luggage · lost luggage" },
  { c: "Du lịch & Địa điểm", v: "cozy", m: "(adj) ấm cúng, dễ chịu", e: "We stayed at a cozy little hotel.", d: "Chúng tôi ở một khách sạn nhỏ ấm cúng.", col: "a cozy cafe · warm and cozy · a cozy corner" },
  { c: "Du lịch & Địa điểm", v: "detour", m: "(n) đường vòng", e: "We took a detour to avoid traffic.", d: "Chúng tôi đi đường vòng để tránh kẹt xe.", col: "take a detour · a short detour · make a detour" },
  { c: "Du lịch & Địa điểm", v: "jet lag", m: "(n) sự mệt mỏi do lệch múi giờ", e: "I had bad jet lag after the flight.", d: "Tôi bị lệch múi giờ nặng sau chuyến bay.", col: "have jet lag · bad jet lag · recover from jet lag" },
  { c: "Du lịch & Địa điểm", v: "vibrant", m: "(adj) sôi động, rực rỡ", e: "The city has a vibrant night market.", d: "Thành phố có khu chợ đêm sôi động.", col: "a vibrant city · vibrant colors · a vibrant atmosphere" },
  { c: "Du lịch & Địa điểm", v: "wander", m: "(v) đi lang thang, dạo quanh", e: "We just wandered around the old town.", d: "Chúng tôi chỉ dạo quanh khu phố cổ.", col: "wander around · wander off · wander the streets" },
  { c: "Du lịch & Địa điểm", v: "remote", m: "(adj) xa xôi, hẻo lánh", e: "They live in a remote village in the mountains.", d: "Họ sống ở một ngôi làng hẻo lánh trên núi.", col: "a remote area · a remote village · remote and isolated" },
  { c: "Du lịch & Địa điểm", v: "landmark", m: "(n) địa danh nổi tiếng", e: "The bridge is a famous landmark.", d: "Cây cầu là một địa danh nổi tiếng.", col: "a famous landmark · a historic landmark · a city landmark" },
  { c: "Du lịch & Địa điểm", v: "spacious", m: "(adj) rộng rãi", e: "The apartment is small but feels spacious.", d: "Căn hộ nhỏ nhưng cảm giác rộng rãi.", col: "a spacious room · bright and spacious · a spacious apartment" },
  { c: "Du lịch & Địa điểm", v: "souvenir", m: "(n) quà lưu niệm", e: "I bought a few souvenirs for my family.", d: "Tôi mua vài món quà lưu niệm cho gia đình.", col: "a souvenir shop · buy souvenirs · a little souvenir" },
  { c: "Du lịch & Địa điểm", v: "breathtaking", m: "(adj) ngoạn mục, đẹp đến nín thở", e: "The view from the top was breathtaking.", d: "Khung cảnh từ trên đỉnh đẹp đến nín thở.", col: "a breathtaking view · breathtaking scenery · absolutely breathtaking" },

  // ===== Thời gian & Thói quen =====
  { c: "Thời gian & Thói quen", v: "routine", m: "(n) thói quen, lề thói hằng ngày", e: "A morning routine sets the tone for the day.", d: "Thói quen buổi sáng định hình cả ngày.", col: "a daily routine · a morning routine · stick to a routine" },
  { c: "Thời gian & Thói quen", v: "punctual", m: "(adj) đúng giờ", e: "He's always punctual for meetings.", d: "Anh ấy luôn đúng giờ trong các cuộc họp.", col: "always punctual · punctual for · punctual and reliable" },
  { c: "Thời gian & Thói quen", v: "postpone", m: "(v) hoãn lại", e: "We had to postpone the trip.", d: "Chúng tôi phải hoãn chuyến đi.", col: "postpone a meeting · postpone until later · postpone indefinitely" },
  { c: "Thời gian & Thói quen", v: "occasionally", m: "(adv) thỉnh thoảng", e: "I occasionally skip breakfast.", d: "Tôi thỉnh thoảng bỏ bữa sáng.", col: "occasionally do · very occasionally · only occasionally" },
  { c: "Thời gian & Thói quen", v: "consistent", m: "(adj) đều đặn, nhất quán", e: "Being consistent matters more than being perfect.", d: "Đều đặn quan trọng hơn là hoàn hảo.", col: "consistent effort · be consistent · consistent results" },
  { c: "Thời gian & Thói quen", v: "rush", m: "(v/n) vội vã / sự vội vã", e: "I always rush in the morning.", d: "Tôi luôn vội vã vào buổi sáng.", col: "in a rush · rush hour · no rush" },
  { c: "Thời gian & Thói quen", v: "overdue", m: "(adj) quá hạn", e: "The library book is overdue.", d: "Cuốn sách thư viện đã quá hạn.", col: "long overdue · an overdue payment · overdue for" },
  { c: "Thời gian & Thói quen", v: "spare time", m: "(n) thời gian rảnh", e: "I read in my spare time.", d: "Tôi đọc sách lúc rảnh.", col: "in my spare time · spend spare time · have spare time" },
  { c: "Thời gian & Thói quen", v: "wind down", m: "(phr.v) thư giãn, hạ nhịp (cuối ngày)", e: "I wind down by reading before bed.", d: "Tôi hạ nhịp bằng việc đọc sách trước khi ngủ.", col: "wind down after work · time to wind down · help me wind down" },
  { c: "Thời gian & Thói quen", v: "hectic", m: "(adj) bận rộn tối mặt", e: "I've had a hectic week at work.", d: "Tôi có một tuần bận tối mặt ở chỗ làm.", col: "a hectic schedule · a hectic day · busy and hectic" },
  { c: "Thời gian & Thói quen", v: "eventually", m: "(adv) cuối cùng (rồi cũng)", e: "He eventually finished the project.", d: "Cuối cùng anh ấy cũng hoàn thành dự án.", col: "eventually realize · eventually agree · happen eventually" },
  { c: "Thời gian & Thói quen", v: "seldom", m: "(adv) hiếm khi", e: "I seldom watch TV these days.", d: "Dạo này tôi hiếm khi xem TV.", col: "seldom seen · very seldom · seldom happens" },
  { c: "Thời gian & Thói quen", v: "last-minute", m: "(adj) vào phút chót", e: "I hate last-minute changes.", d: "Tôi ghét những thay đổi vào phút chót.", col: "a last-minute change · at the last minute · last-minute plans" },
  { c: "Thời gian & Thói quen", v: "juggle", m: "(v) cân bằng nhiều việc một lúc", e: "She juggles work and study.", d: "Cô ấy cân bằng cả việc làm và việc học.", col: "juggle work and family · juggle multiple tasks · juggle responsibilities" },
  { c: "Thời gian & Thói quen", v: "downtime", m: "(n) thời gian nghỉ ngơi", e: "Everyone needs some downtime to recharge.", d: "Ai cũng cần thời gian nghỉ để nạp lại năng lượng.", col: "some downtime · need downtime · enjoy downtime" },
];

export const vocab = raw.map((x) => ({ ...x, id: x.c + "::" + x.v }));
export default vocab;
